<h1 style="color:blueviolet;text-align:center;font-weight:700;">Categorical Variables and One Hot Encoding</h1>

---

In [1]:
import pandas as pd

df = pd.read_csv("homeprices.csv")
df.head()

              town  area   price
0  monroe township  2600  550000
1  monroe township  3000  565000
2  monroe township  3200  610000
3  monroe township  3600  680000
4  monroe township  4000  725000

### ***1) Using pandas to create dummy variables***

In [2]:
dummies = pd.get_dummies(df.town)
dummies.head()

   monroe township  robinsville  west windsor
0             True        False         False
1             True        False         False
2             True        False         False
3             True        False         False
4             True        False         False

In [3]:
dummies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   monroe township  13 non-null     bool
 1   robinsville      13 non-null     bool
 2   west windsor     13 non-null     bool
dtypes: bool(3)
memory usage: 171.0 bytes

- ***We have to agian convert it to numerical values like `1 for True & 0 for False`***
- ***Instead of doing this we can directly use `LabelEncoder` & `OnehotEncoder` from the `Scikit learn library`***

### ***2) Label Encoder & One Hot Encoder***

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [5]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [6]:
X = dfle[['town','area']].values
X

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [7]:
y = dfle.price
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

- ***Now use one hot encoder to create dummy variables for each of the town***

In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('town', OneHotEncoder(), [0])], remainder = 'passthrough')

In [9]:
X = ct.fit_transform(X)
X

array([[1.0e+00, 0.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.0e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.2e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 2.9e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.1e+03],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.6e+03]])

In [10]:
X = X[:,1:]
print(X)

[[0.0e+00 0.0e+00 2.6e+03]
 [0.0e+00 0.0e+00 3.0e+03]
 [0.0e+00 0.0e+00 3.2e+03]
 [0.0e+00 0.0e+00 3.6e+03]
 [0.0e+00 0.0e+00 4.0e+03]
 [0.0e+00 1.0e+00 2.6e+03]
 [0.0e+00 1.0e+00 2.8e+03]
 [0.0e+00 1.0e+00 3.3e+03]
 [0.0e+00 1.0e+00 3.6e+03]
 [1.0e+00 0.0e+00 2.6e+03]
 [1.0e+00 0.0e+00 2.9e+03]
 [1.0e+00 0.0e+00 3.1e+03]
 [1.0e+00 0.0e+00 3.6e+03]]

In [11]:
from sklearn import linear_model
model = linear_model.LinearRegression()

In [12]:
model.fit(X,y)

LinearRegression()

In [13]:
model.predict([[0,1,3400]]) # 3400 sqr ft home in west windsor

array([681241.6684584])

In [14]:
model.predict([[1,0,2800]]) # 2800 sqr ft home in robbinsville

array([590775.63964739])

In [15]:
model.score(X,y)*100

95.73929037221873

---

### <font style="color:darkorange;font-weight:700;">Diff. Types of Encoding:</font>

1. ***Label Encoding*** is used when **`categories are nominal (no order) and converts them into integers.`**
2. ***One-Hot Encoding*** is used to **`create binary columns for each category`, useful when there is `no ordinal relationship`**.
3. ***Ordinal Encoding*** is used for **`categorical features with a meaningful order`**.

`Example Scenario:`
Imagine we have a dataset of fruits with the following information:

- **Fruit**: Names of the fruits (categorical feature)
- **Size**: The size of the fruit (ordinal feature — small, medium, large)
- **Color**: The color of the fruit (categorical feature)

In [16]:
# Sample data
data = {
    'Fruit': ['Apple', 'Banana', 'Cherry', 'Apple', 'Cherry'],
    'Size': ['Small', 'Medium', 'Large', 'Small', 'Large'],
    'Color': ['Red', 'Yellow', 'Red', 'Green', 'Red']
}

df = pd.DataFrame(data)
df

    Fruit    Size   Color
0   Apple   Small     Red
1  Banana  Medium  Yellow
2  Cherry   Large     Red
3   Apple   Small   Green
4  Cherry   Large     Red

**1. Label Encoding (for the Fruit column)**\
Label Encoding assigns a unique integer to each category. Let’s apply Label Encoding to the Fruit column:

In [17]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Fruit_LabelEncoded'] = le.fit_transform(df['Fruit'])
df

    Fruit    Size   Color  Fruit_LabelEncoded
0   Apple   Small     Red                   0
1  Banana  Medium  Yellow                   1
2  Cherry   Large     Red                   2
3   Apple   Small   Green                   0
4  Cherry   Large     Red                   2

**2. One-Hot Encoding (for the Color column)**\
One-Hot Encoding creates binary columns for each category. Let’s apply One-Hot Encoding to the Color column:

In [18]:
# One-Hot Encoding for 'Color'
ohe = OneHotEncoder(sparse_output=False)  # Ensure it returns a dense array
color_encoded = ohe.fit_transform(df[['Color']])

# Create new columns for one-hot encoded 'Color'
color_columns = ohe.get_feature_names_out(['Color'])
df_color_encoded = pd.DataFrame(color_encoded, columns=color_columns)

# Concatenate original DataFrame with one-hot encoded columns
df_final = pd.concat([df, df_color_encoded], axis=1)

df_final

,Fruit,Size,Color,Fruit_LabelEncoded,Color_Green,Color_Red,Color_Yellow
0,Apple,Small,Red,0,0.0,1.0,0.0
1,Banana,Medium,Yellow,1,0.0,0.0,1.0
2,Cherry,Large,Red,2,0.0,1.0,0.0
3,Apple,Small,Green,0,1.0,0.0,0.0
4,Cherry,Large,Red,2,0.0,1.0,0.0

**3. Ordinal Encoding (for the Size column)**\
- Ordinal Encoding assigns integers based on the order of categories. 
- Since Size has a natural order (Small < Medium < Large), we can encode it as:

In [19]:
from sklearn.preprocessing import OrdinalEncoder

size_order = ['Small', 'Medium', 'Large']
ordinal_encoder = OrdinalEncoder(categories=[size_order])
df['Size_OrdinalEncoded'] = ordinal_encoder.fit_transform(df[['Size']]).astype(int)
df

    Fruit    Size   Color  Fruit_LabelEncoded  Size_OrdinalEncoded
0   Apple   Small     Red                   0                    0
1  Banana  Medium  Yellow                   1                    1
2  Cherry   Large     Red                   2                    2
3   Apple   Small   Green                   0                    0
4  Cherry   Large     Red                   2                    2

***similary it can be done using map function:***

In [20]:
size_mapping = {'Small': 0, 'Medium': 1, 'Large': 2}
df['Size_OE_en_map'] = df['Size'].map(size_mapping)
df

,Fruit,Size,Color,Fruit_LabelEncoded,Size_OrdinalEncoded,Size_OE_en_map
0,Apple,Small,Red,0,0,0
1,Banana,Medium,Yellow,1,1,1
2,Cherry,Large,Red,2,2,2
3,Apple,Small,Green,0,0,0
4,Cherry,Large,Red,2,2,2