<h1 style="color:blueviolet; font-weight:700; text-align:center">Mean, Median, Mode, Percentile</h1>

### 1. `Mean`:The mean is the ***average of a dataset***.

Example\
**Given data**: `[10, 20, 30, 40, 50]`\
**Mean** = (10 + 20 + 30 + 40 + 50) / 5 = 30

In [1]:
import numpy as np

data = [10,20,30,40,50]
mean = np.mean(data)
print(f"Mean: {int(mean)}")

Mean: 30

### 2. `Median`: The median is the ***middle value*** when the data is sorted.

In [2]:
import pandas as pd

df = pd.read_csv("income.csv", names=["name","income"], skiprows=[0])
df

        name    income
0        Rob      5000
1      Rafiq      6000
2       Nina      4000
3      Sofia      7500
4      Mohan      8000
5        Tao      7000
6  Elon Musk  10000000

- In the dataset we can clearly see that taking the `mean for the data set will give an terrible average!`
- As Mr. Elon Musk is an outlier here...Because of which the monthly average would be around **1.43 million**
- `Outlier` is a dataset that is ***very different from the rest of the data points***
- In this situation taking a **`median would be a much better option to remove the outlier`**

In [3]:
# print the stats for the whole income column like this:
df.income.describe()

count    7.000000e+00
mean     1.433929e+06
std      3.777283e+06
min      4.000000e+03
25%      5.500000e+03
50%      7.000000e+03
75%      7.750000e+03
max      1.000000e+07
Name: income, dtype: float64

- ***The percentile tells you what percentage of data falls below a certain value.***
- In pandas perecntile == quantile. It tells `what % of data falls below a certain value`

In [4]:
print(df["income"].quantile(0))

4000.0

In [5]:
print(df.income.quantile(0.25)) # by default it will consider the average btw lower & higher bound in a median

5500.0

In [6]:
print(df.income.quantile(0.25,interpolation="higher")) # it will consider the upper/higher bound in a median

6000

In [7]:
print(df.income.quantile(0.25,interpolation="lower")) # it will consider the lower bound in a median

5000

In [8]:
print(df.income.quantile(0.75))

7750.0

In [9]:
print(df.income.quantile(1))

10000000.0

In [10]:
percentile_99 = df.income.quantile(0.99)
print(percentile_99)

9400479.999999994

In [11]:
df[df.income>percentile_99]

        name    income
6  Elon Musk  10000000

In [12]:
df.loc[3, 'income'] = np.nan
df

        name      income
0        Rob      5000.0
1      Rafiq      6000.0
2       Nina      4000.0
3      Sofia         NaN
4      Mohan      8000.0
5        Tao      7000.0
6  Elon Musk  10000000.0

<h4>• Now see using mean gives an horrible average</h4>

In [13]:
print(df.income.mean())

1671666.6666666667

In [14]:
df_new = df.fillna(df.income.mean())
df_new

        name        income
0        Rob  5.000000e+03
1      Rafiq  6.000000e+03
2       Nina  4.000000e+03
3      Sofia  1.671667e+06
4      Mohan  8.000000e+03
5        Tao  7.000000e+03
6  Elon Musk  1.000000e+07

<h4>• Now using median gives better result</h4>

In [15]:
df_new = df.fillna(df.income.median())
df_new

        name      income
0        Rob      5000.0
1      Rafiq      6000.0
2       Nina      4000.0
3      Sofia      6500.0
4      Mohan      8000.0
5        Tao      7000.0
6  Elon Musk  10000000.0

### 3. `Mode`: value that appears most frequently in a dataset

Example:\
Given data: `[10, 20, 20, 30, 40, 50]`\
Mode = 20 (since it appears twice)

In [16]:
data_with_mode = [10, 20, 20, 30, 40, 50]

values, counts = np.unique(data_with_mode, return_counts=True)
mode = values[np.argmax(counts)]

print("Mode:", mode)

Mode: 20