<h1 style="color:darkorange;font-weight:700;text-align:center">Naive Bayes</h1>

---
- We know Bayes Theorem:
  ```P(A|B) = P(B|A).P(A)/P(B)```
  
- We call this **`Naive Bayes`** because we ***make a naive assumption on the features that they will be independent variables. Like if we drop them also it will not effect the main goal => to make accurate prediction for the problem satatement.***

In [1]:
import pandas as pd

df = pd.read_csv("titanic.csv")
df[:5]

,PassengerId,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

***Here we are making naive assumptions & dropping some columns assuming it will not affect the survival on these columns***

In [2]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

   Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [3]:
inputs = df.drop('Survived',axis="columns")
target = df.Survived

In [4]:
inputs.Sex

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: object

In [5]:
dummies = pd.get_dummies(inputs.Sex) 

# Convert the boolean values in the dummy variables to 1 and 0 explicitly
dummies = dummies.astype(int)
dummies.head()

   female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [6]:
inputs = pd.concat([inputs,dummies],axis="columns")
inputs.head()

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0
3       1  female  35.0  53.1000       1     0
4       3    male  35.0   8.0500       0     1

In [7]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1

In [8]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [9]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [10]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

   Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [12]:
len(X_train)

623

In [13]:
len(X_test)

268

In [14]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [15]:
model.fit(X_train,y_train)

GaussianNB()

In [16]:
model.score(X_test,y_test)

0.7723880597014925

In [17]:
X_test[0:10]

     Pclass        Age     Fare  female
728       2  25.000000  26.0000       0
236       2  44.000000  26.0000       0
732       2  29.699118   0.0000       0
136       1  19.000000  26.2833       1
621       1  42.000000  52.5542       0
277       2  29.699118   0.0000       0
597       3  49.000000   0.0000       0
202       3  34.000000   6.4958       0
884       3  25.000000   7.0500       0
222       3  51.000000   8.0500       0

In [18]:
y_test[0:10]

728    0
236    0
732    0
136    1
621    1
277    0
597    0
202    0
884    0
222    0
Name: Survived, dtype: int64

In [19]:
model.predict(X_test[0:10])

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [20]:
model.predict_proba(X_test[:10])

array([[0.9029062 , 0.0970938 ],
       [0.9214382 , 0.0785618 ],
       [0.91391956, 0.08608044],
       [0.05720362, 0.94279638],
       [0.68480885, 0.31519115],
       [0.91391956, 0.08608044],
       [0.96404768, 0.03595232],
       [0.96099155, 0.03900845],
       [0.95546044, 0.04453956],
       [0.96528237, 0.03471763]])