<h1 style="color:orange;">DATA FRAMES</h1>

- Dataframes is a ***main object*** in **Pandas**.
- It is used to `represent data with rows & columns (tabular/excel spreadsheet)`

In [1]:
import pandas as pd
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}
df = pd.DataFrame(weather_data)
df = pd.read_csv("weather_data.csv")
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [2]:
df.shape

(6, 4)

<h3 style="color:blue;">Rows</h3>

In [3]:
df.head() #df.head(3)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [4]:
df.tail() #df.tail(2)

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [5]:
# Data frames can also be sliced 
# just like other datastructures like list & tuples in Python

df[2:5]

        day  temperature  windspeed event
2  1/3/2017           28          2  Snow
3  1/4/2017           24          7  Snow
4  1/5/2017           32          4  Rain

<h3 style="color:blue;">Columns</h3>

In [6]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [7]:
df['day'] #df.day

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [8]:
type(df.day)

pandas.core.series.Series

In [9]:
df[['day','temperature']]

        day  temperature
0  1/1/2017           32
1  1/2/2017           35
2  1/3/2017           28
3  1/4/2017           24
4  1/5/2017           32
5  1/6/2017           31

<h2 style="color:blue;">Operations on Data frames</h2>

In [10]:
df['temperature'].max() #df.temperature.max()

np.int64(35)

In [11]:
df[df['temperature']>=32]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain

In [12]:
df['day'][df['temperature'] == df['temperature'].max()] # Kinda doing SQL in pandas

1    1/2/2017
Name: day, dtype: object

In [13]:
df[df['temperature'] == df['temperature'].max()] #Extracting the data frame by quering like SQL in pandas

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [14]:
df['temperature'].std()

np.float64(3.8297084310253524)

In [15]:
df['event'].max() # But mean() won't work since data type is string

'Sunny'

In [16]:
df.describe() #For printing all the statistics

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

`List of all operations on pandas dataframe`: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html

<h3 style="color:blue;">Set Index</h3>

In [17]:
df.set_index('day') #df.set_index('day', inplace=True)

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [18]:
df.head(3)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [19]:
df.set_index('day', inplace=True) #changing in the original dataframe
df

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [20]:
df.index

Index(['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'], dtype='object', name='day')

In [21]:
df.loc['1/2/2017']

temperature       35
windspeed          7
event          Sunny
Name: 1/2/2017, dtype: object

In [22]:
df.reset_index(inplace=True)
df.head()

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [23]:
df.set_index('event',inplace=True) # this is kind of building a hash map using event as a key
df

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [24]:
df.loc['Snow']

            day  temperature  windspeed
event
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7