<h1 style="color:salmon;text-align:center;">Handel Missing Data - replace method</h1>

In [1]:
import pandas as pd
import numpy as np

df= pd.read_csv("weather_data.csv")
df

          day temperature windspeed  event
0  01-01-2017        32 F     6 mph   Rain
1  01-02-2017      -99999     7 mph  Sunny
2  01-03-2017          28    -99999   Snow
3  01-04-2017      -99999         7      0
4  01-05-2017        32 C    -88888   Rain
5  01-06-2017          31         2  Sunny
6  01-06-2017          34         5      0

### replacing a single value

In [2]:
new_df = df.replace(-99999, np.nan)
new_df

          day temperature windspeed  event
0  01-01-2017        32 F     6 mph   Rain
1  01-02-2017      -99999     7 mph  Sunny
2  01-03-2017          28    -99999   Snow
3  01-04-2017      -99999         7      0
4  01-05-2017        32 C    -88888   Rain
5  01-06-2017          31         2  Sunny
6  01-06-2017          34         5      0

### Replacing list with single values

In [3]:
new_df = df.replace([-99999, -88888], np.nan)
new_df

          day temperature windspeed  event
0  01-01-2017        32 F     6 mph   Rain
1  01-02-2017      -99999     7 mph  Sunny
2  01-03-2017          28    -99999   Snow
3  01-04-2017      -99999         7      0
4  01-05-2017        32 C    -88888   Rain
5  01-06-2017          31         2  Sunny
6  01-06-2017          34         5      0

### Replacing per column

In [4]:
new_df = df.replace({
        'temperature': -99999,
        'windspeed': -99999,
        'event': '0'
    }, np.nan)
new_df

          day temperature windspeed  event
0  01-01-2017        32 F     6 mph   Rain
1  01-02-2017      -99999     7 mph  Sunny
2  01-03-2017          28    -99999   Snow
3  01-04-2017      -99999         7    NaN
4  01-05-2017        32 C    -88888   Rain
5  01-06-2017          31         2  Sunny
6  01-06-2017          34         5    NaN

### Replacing by using mapping

In [5]:
new_df = df.replace({
        -99999: np.nan,
        'no event': 'Sunny',
    })
new_df

          day temperature windspeed  event
0  01-01-2017        32 F     6 mph   Rain
1  01-02-2017      -99999     7 mph  Sunny
2  01-03-2017          28    -99999   Snow
3  01-04-2017      -99999         7      0
4  01-05-2017        32 C    -88888   Rain
5  01-06-2017          31         2  Sunny
6  01-06-2017          34         5      0

### Regex - Regular Expression

In [7]:
# when windspeed is 6 mph, 7 mph etc. & temperature is 32 F, 28 F etc.
new_df = df.replace({'temperature': '[A-Za-z]', 'windspeed': '[a-z]'},'', regex=True) 
new_df

          day temperature windspeed  event
0  01-01-2017         32         6    Rain
1  01-02-2017      -99999        7   Sunny
2  01-03-2017          28    -99999   Snow
3  01-04-2017      -99999         7      0
4  01-05-2017         32     -88888   Rain
5  01-06-2017          31         2  Sunny
6  01-06-2017          34         5      0

### Replacing list with another list

In [8]:
df = pd.DataFrame({
    'score': ['exceptional','average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [12]:
pd.set_option('future.no_silent_downcasting', True)
df.replace(['poor', 'average', 'good', 'exceptional'], [1,2,3,4])
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica